//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFInal2021Beta.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabla
    {
        public int ProgramaId { get; set; }
        public string Nombre { get; set; }
        public string Categoria { get; set; }
        public System.DateTime Fecha_Alta { get; set; }
    }
}
